
/* Remover Trigger */

DROP TRIGGER TRIG_ORDER_DELIVERY;

/* Remove Procedure*/

DROP PROCEDURE PROC_CUSTOMER_DETAILS;

/*Removal of foreign keys first*/

ALTER TABLE Feedback 
DROP CONSTRAINT FK_FEEDBACK_OID;

ALTER TABLE Item_Toppings_Details 
DROP CONSTRAINT FK_ITEMTOPPINGSD_OID;


ALTER TABLE Item_Toppings_Details 
DROP CONSTRAINT FK_ITEMTOPPINGSD_TID;

ALTER TABLE Item_Toppings_Details 
DROP CONSTRAINT FK_ITEMTOPPINGS_IID;

ALTER TABLE Order_Details_Pizza
DROP CONSTRAINT FK_ORDERD_PIZZAD_PIZZAID;

ALTER TABLE Order_Details_Pizza
DROP CONSTRAINT FK_ORDERD_SIZED_SID;

ALTER TABLE Pizza_Price_Details
DROP CONSTRAINT FK_PIZZAPRICED_PID;

ALTER TABLE Pizza_Price_Details
DROP CONSTRAINT FK_PIZZAPRICED_SID;

ALTER TABLE Status
DROP CONSTRAINT FK_STATUS_ID;

ALTER TABLE Toppings_Price_Details
DROP CONSTRAINT FK_TOPPINGSPRICED_TID;

ALTER TABLE Order_Delivery
DROP CONSTRAINT FK_CUST_ID;

ALTER TABLE Order_Delivery
DROP CONSTRAINT FK_EMP_ID;

ALTER TABLE Order_Delivery
DROP CONSTRAINT FK_VEHICLE_ID;


/*--------------------------------------------------------------------------------------------------*/

/*Removal of Primary Keys*/

ALTER TABLE Customer_Details
DROP CONSTRAINT PK_CUSTOMER_ID;

ALTER TABLE Employee
DROP CONSTRAINT PK_EMP_ID;

ALTER TABLE Order_Delivery
DROP CONSTRAINT PK_ORDER_ID;

ALTER TABLE Order_Details_Pizza
DROP CONSTRAINT PK_ITEM_ID;

ALTER TABLE Pizza_Details
DROP CONSTRAINT PK_PIZZA_ID;

ALTER TABLE Size_Details
DROP CONSTRAINT PK_SIZE_ID;

ALTER TABLE Status
DROP CONSTRAINT PK_STATUS_ID;

ALTER TABLE Toppings_Details
DROP CONSTRAINT PK_TOPPING_ID;

ALTER TABLE Vehicle_Details
DROP CONSTRAINT PK_VEHICLE_ID;

/*---------------------------------------------------------------------------------------------*/

/* Drop Tables */

DROP TABLE ORDER_DETAILS_PIZZA;

DROP TABLE ORDER_DELIVERY;

DROP TABLE ITEM_TOPPINGS_DETAILS;

DROP TABLE PIZZA_DETAILS;

DROP TABLE PIZZA_PRICE_DETAILS;

DROP TABLE SIZE_DETAILS;

DROP TABLE TOPPINGS_DETAILS;

DROP TABLE TOPPINGS_PRICE_DETAILS;

DROP TABLE CUSTOMER_DETAILS;

DROP TABLE EMPLOYEE;

DROP TABLE FEEDBACK;

DROP TABLE VEHICLE_DETAILS;

DROP TABLE STATUS;

PURGE  RECYCLEBIN;




